export const ROOM_COLORS = ["red", "blue", "purple", "yellow", "orange", "green", "gray", "black"];

export const COLOR_NAME_TO_VALUE = {
    "red": "#dc3545",
    "blue": "#007bff",
    "purple": "#6f42c1",
    "yellow": "#ffc107",
    "orange": "#fd7e14",
    "green": "#28a745",
    "gray": "#808080",
    "black": "#000000",
};

// Shortened for brevity - include the full list from your original code
export     const PREDEFINED_ROOMS = [
    { name: "Foundation", color: "blue", exit_no: 3, rarity: "rare", extra_data: [ {permanent: true}]},
    // { name: "Entrance Hall", color: "blue", exit_no: 4, rarity: "N/A", extra_data: [ {permanent: true}]},
    { name: "Spare Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 3 }] },
    { name: "Rotunda", color: "blue", exit_no: 2, rarity: "rare", extra_data: [{ gems: 3}]},
    { name: "Parlor", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 5 }] },
    { name: "Billiard Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 6 }] },
    { name: "Closet", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 9 }] },
    { name: "Walk-in Closet", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 10, gems: 1 }] },
    { name: "Attic", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 11, gems: 3 }] },
    { name: "Storeroom", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 12 }] },
    { name: "Nook", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 13 }] },
    { name: "Garage", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 14, gems: 1 }] },
    { name: "Music Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 15, gems: 2 }] },
    { name: "Locker Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 16, gems: 1 }] },
    { name: "Den", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 17 }] },
    { name: "Wine Cellar", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 18 }] },
    { name: "Trophy Room", color: "blue", exit_no: 2, rarity: "rare", extra_data: [{gems: 5, rewards: {gems: 8}}]},
    { name: "Ball Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 20, gems: 2 }] },
    { name: "Pantry", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 21 }] },
    { name: "Rumpus Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 22, gems: 1 }] },
    { name: "Vault", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 23, gems: 3 }] },
    { name: "Office", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 24, gems: 2 }] },
    { name: "Drawing Room", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 25, gems: 1 }] },
    { name: "Study", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 26 }] },
    { name: "Library", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 27 }] },
    { name: "Chamber of Mirrors", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 28 }] },
    { name: "The Pool", color: "blue", exit_no: 3, rarity: "standard", extra_data: [{ number: 29, gems: 1 }] },
    { name: "Drafting Studio", color: "blue", exit_no: 2, rarity: "rare", extra_data: [{gems: 2}]},
    { name: "Utility Closet", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 31 }] },
    { name: "Boiler Room", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 32, gems: 1 }] },
    { name: "Pump Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 33 }] },
    { name: "Security", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 34, gems: 1 }] },
    { name: "Workshop", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 35 }] },
    { name: "Laboratory", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 36, gems: 1 }] },
    { name: "Sauna", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 37 }] },
    { name: "Coat Check", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 38 }] },
    { name: "Mail Room", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 39 }] },
    { name: "Freezer", color: "blue", exit_no: 1, rarity: "rare", extra_data: []},
    { name: "Dining Room", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 41 }] },
    { name: "Observatory", color: "blue", exit_no: 1, rarity: "common", extra_data: [{ number: 42, gems: 1 }] },
    { name: "Conference Room", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 43 }] },
    { name: "Aquarium", color: "blue", exit_no: 3, rarity: "common", extra_data: [{ number: 44 }] },
    { name: "Bedroom", color: "purple", exit_no: 1, rarity: "common", extra_data: [] },
    { name: "Boudoir", color: "purple", exit_no: 1, rarity: "standard", extra_data: [] },
    { name: "Guest Bedroom", color: "purple", exit_no: 1, rarity: "common", extra_data: [] },
    { name: "Nursery", color: "purple", exit_no: 1, rarity: "common", extra_data: [{gems: 1}] },
    { name: "Servant's Quarters", color: "purple", exit_no: 1, rarity: "unusual", extra_data: [{gems: 1}]},
    { name: "Bunk Room", color: "purple", exit_no: 1, rarity: "unusual", extra_data: [] },
    { name: "Her Ladyship's Chamber", color: "purple", exit_no: 1, rarity: "standard", extra_data: [] },
    { name: "Master Bedroom", color: "purple", exit_no: 1, rarity: "rare", extra_data: [{gems: 2}] },
    { name: "Hallway", color: "orange", exit_no: 3, rarity: "common", extra_data: [] },
    { name: "West Wing Hall", color: "orange", exit_no: 3, rarity: "standard", extra_data: [] },
    { name: "East Wing Hall", color: "orange", exit_no: 3, rarity: "unusual", extra_data: [] },
    { name: "Corridor", color: "orange", exit_no: 1, rarity: "common", extra_data: [] },
    { name: "Passageway", color: "orange", exit_no: 4, rarity: "common", extra_data: [{gems: 2}] },
    { name: "Secret Passage", color: "orange", exit_no: 1, rarity: "unusual", extra_data: [{gems: 1}] },
    { name: "Foyer", color: "orange", exit_no: 2, rarity: "unusual", extra_data: [{gems: 2}]},
    { name: "Great Hall", color: "orange", exit_no: 4, rarity: "unusual", extra_data: [] },
    { name: "Terrace", color: "green", exit_no: 1, rarity: "standard", extra_data: [] },
    { name: "Patio", color: "green", exit_no: 1, rarity: "standard", extra_data: [] },
    { name: "Courtyard", color: "green", exit_no: 3, rarity: "standard", extra_data: [] },
    { name: "Cloister", color: "green", exit_no: 4, rarity: "unusual", extra_data: [] },
    { name: "Veranda", color: "green", exit_no: 1, rarity: "unusual", extra_data: [] },
    { name: "Greenhouse", color: "green", exit_no: 1, rarity: "common", extra_data: [] },
    { name: "Morning Room", color: "green", exit_no: 2, rarity: "common", extra_data: [] },
    { name: "Secret Garden", color: "green", exit_no: 3, rarity: "rare", extra_data: [] },
    { name: "Commissary", color: "yellow", exit_no: 2, rarity: "standard", extra_data: [{gems: 1}] },
    { name: "Kitchen", color: "yellow", exit_no: 2, rarity: "common", extra_data: [{gems: 1}] },
    { name: "Locksmith", color: "yellow", exit_no: 1, rarity: "unusual", extra_data: [{gems: 1}] },
    { name: "Showroom", color: "yellow", exit_no: 2, rarity: "rare", extra_data: [{gems: 2}] },
    { name: "Laundry Room", color: "yellow", exit_no: 1, rarity: "rare", extra_data: [{gems: 1}] },
    { name: "Bookshop", color: "yellow", exit_no: 2, rarity: "rare", extra_data: [{gems: 1}] },
    { name: "Armory", color: "yellow", exit_no: 2, rarity: "standard", extra_data: []},
    { name: "Mount Holly Giftshop", color: "yellow", exit_no: 3, rarity: "rare", extra_data: []},
    { name: "Lavatory", color: "red", exit_no: 1, rarity: "standard", extra_data: [] },
    { name: "Chapel", color: "red", exit_no: 3, rarity: "common", extra_data: [] },
    { name: "Maid's Chamber", color: "red", exit_no: 2, rarity: "unusual", extra_data: [] },
    { name: "Archives", color: "red", exit_no: 4, rarity: "unusual", extra_data: [] },
    { name: "Gymnasium", color: "red", exit_no: 3, rarity: "rare", extra_data: [] },
    { name: "Darkroom", color: "red", exit_no: 3, rarity: "standard", extra_data: [] },
    { name: "Weight Room", color: "red", exit_no: 4, rarity: "rare", extra_data: [] },
    { name: "Furnace", color: "red", exit_no: 1, rarity: "rare", extra_data: [] },
    { name: "Kennel", color: "blue", exit_no: 2, rarity: "standard", extra_data: []},
    { name: "Classroom", color: "blue", exit_no: 2, rarity: "unusual", extra_data: [{gems: 1}]},
    { name: "Dormitory", color: "purple", exit_no: 2, rarity: "standard", extra_data: []},
    { name: "Vestibule", color: "orange", exit_no: 4, rarity: "rare", extra_data: [{gems: 2}]},
    { name: "Casino", color: "yellow", exit_no: 2, rarity: "rare", extra_data: [{gems: 2}]},
    { name: "Planetarium", color: "blue", exit_no: 1, rarity: "standard", extra_data: []},
    { name: "Mechanarium", color: "blue", exit_no: 1, rarity: "unusual", extra_data: []},
    { name: "Treasure Trove", color: "black", exit_no: 2, rarity: "unusual", extra_data: [{gems: 1}]},
    { name: "Tunnel", color: "orange", exit_no: 2, rarity: "standard", extra_data: []},
    { name: "Conservatory", color: "green", exit_no: 2, rarity: "unusual", extra_data: [] },
    { name: "Lost & Found", color: "red", exit_no: 2, rarity: "unusual", extra_data: []},
    { name: "Closed Exhibit", color: "red", exit_no: 3, rarity: "rare", extra_data: [] },
    { name: "Toolshed", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Shelter", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Schoolhouse", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Shrine", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Root Cellar", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Hovel", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Trading Post", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Tomb", color: "gray", exit_no: 1, rarity: "common", extra_data: [{ outer: true }] },
    { name: "Throne Room", color: "blue", exit_no: 2, rarity: "rare", extra_data: []},
];

export const ROWS = 9;
export const COLS = 5;
export const CELL_SIZE = 80;
export const START_DATE = new Date(1993, 10, 7); // November is month 10 (0-indexed)
export const OUTER_ROOM_ID = "OuterRoom";
export const ANTECHAMBER_ID = `R9C3`;
export const ENTRANCE_HALL_ID = `R1C3`;
